name: OpenWrt-ImmortalWrt-24.10-Compiler
on:
  workflow_dispatch:
  push:
    tags:
      - 'immortal24.10-*'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  CONFIG_FILE: immortal24.10.config
  TZ: Asia/Shanghai

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 步骤2：初始化编译环境
      - name: Setup Build Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev

      # 步骤3：加载指定配置文件
      - name: Apply Custom Configuration
        run: |
          if [ -f "$CONFIG_FILE" ]; then
            cp $CONFIG_FILE .config
            make defconfig
          else
            echo "❌ 配置文件 $CONFIG_FILE 未找到，终止编译流程"
            exit 1
          fi

      # 步骤4：内核编译与固件生成
      - name: Build Firmware
        run: |
          make -j$(nproc) download
          make -j$(nproc) || make -j1 V=s

      # 步骤5：产物归档
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: immortalwrt-24.10-binaries
          path: bin/targets/*/*
