name: Build ImmortalWrt 24.10

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: immortal24.10.config
  DIY_P1: diy-24.10-part1.sh
  DIY_P2: diy-24.10-part2.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
    # 第一步：检出用户配置仓库
    - name: Checkout Configuration Files
      uses: actions/checkout@v4
      with:
        path: config-repo  # 用户配置文件存放目录

    # 第二步：设置高级工具链
    - name: Setup Advanced Toolchains
      run: |
        # 安装 LLVM 16
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        # 安装 Python 3.12
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt-get update -y
        sudo apt-get install -y \
          clang-16 lld-16 \
          python3.12 python3.12-dev \
          libpython3.12-dev

    # 第三步：安装基础依赖
    - name: Install Base Dependencies
      run: |
        sudo apt-get install -y $(cat config-repo/depends-24.10.txt)
        # 创建工具链符号链接
        sudo ln -sf /usr/bin/clang-16 /usr/bin/clang
        sudo ln -sf /usr/bin/clang++-16 /usr/bin/clang++

    # 第四步：克隆 ImmortalWrt 源码
    - name: Clone Source Code
      run: |
        git clone "$REPO_URL" -b "$REPO_BRANCH" openwrt
        # 复制配置文件到正确位置
        cp config-repo/"$CONFIG_FILE" openwrt/.config
        cp config-repo/"$DIY_P1" openwrt/
        cp config-repo/"$DIY_P2" openwrt/

    # 第五步：应用自定义配置
    - name: Apply Custom Scripts
      working-directory: openwrt
      run: |
        chmod +x "$DIY_P1" "$DIY_P2"
        ./"$DIY_P1"
        ./"$DIY_P2"

    # 第六步：下载软件包
    - name: Download Packages
      working-directory: openwrt
      run: |
        make -j$(nproc) download || make -j1 V=s download
        find dl -size -1024c -delete

    # 第七步：编译固件
    - name: Compile Firmware
      working-directory: openwrt
      env:
        CC: clang
        CXX: clang++
        PATH: "/usr/lib/llvm-16/bin:$PATH"
      run: |
        make -j$(($(nproc) + 1)) || make -j1 V=s

    # 第八步：上传编译成果
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-24.10-bin
        path: openwrt/bin/targets/
        retention-days: 7
