name: Build ImmortalWrt 24.10

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: immortal24.10.config
  DIY_P1: diy-24.10-part1.sh
  DIY_P2: diy-24.10-part2.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Toolchains
      run: |
        # 添加 LLVM 16 官方源
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        # 添加 Python 3.12 源
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        # 更新源
        sudo apt-get update -y

    - name: Install Dependencies
      run: |
        # 安装新版工具链
        sudo apt-get install -y \
          clang-16 lld-16 lldb-16 \
          python3.12 python3.12-dev \
          libpython3.12-dev
        # 安装基础依赖
        xargs -a depends-24.10.txt sudo apt-get install -y
        # 创建符号链接
        sudo ln -sf /usr/bin/clang-16 /usr/bin/clang
        sudo ln -sf /usr/bin/clang++-16 /usr/bin/clang++

    - name: Clone Source Code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cp $CONFIG_FILE openwrt/.config
        cp $DIY_P1 openwrt/
        cp $DIY_P2 openwrt/

    - name: Apply Custom Scripts
      working-directory: openwrt
      run: |
        chmod +x ../$DIY_P1 ../$DIY_P2
        ../$DIY_P1
        ../$DIY_P2

    - name: Download Packages
      working-directory: openwrt
      run: |
        make -j$(nproc) download || make -j1 V=s download
        find dl -size -1024c -delete

    - name: Compile Firmware
      working-directory: openwrt
      run: |
        export PATH="/usr/lib/llvm-16/bin:$PATH"
        make -j$(($(nproc) + 1)) || make -j1 V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-24.10-bin
        path: openwrt/bin/targets/
        retention-days: 7
