name: Build ImmortalWrt 24.10

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: immortal24.10.config
  DIY_P1: diy-24.10-part1.sh
  DIY_P2: diy-24.10-part2.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
    # 关键修复：先检出用户仓库
    - name: Checkout Configuration Files
      uses: actions/checkout@v4
      with:
        path: config-repo

    - name: Setup Toolchains
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt-get update -y
        sudo apt-get install -y clang-16 lld-16 python3.12

    - name: Clone ImmortalWrt Source
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        # 从用户配置目录复制文件
        cp config-repo/$CONFIG_FILE openwrt/.config
        cp config-repo/$DIY_P1 openwrt/
        cp config-repo/$DIY_P2 openwrt/

    - name: Apply Custom Scripts
      working-directory: openwrt
      run: |
        chmod +x $DIY_P1 $DIY_P2
        ./$DIY_P1
        ./$DIY_P2

       - name: Download Packages
      working-directory: openwrt
      run: |
        make -j$(nproc) download || make -j1 V=s download
        find dl -size -1024c -delete

    - name: Compile Firmware
      working-directory: openwrt
      run: |
        export PATH="/usr/lib/llvm-16/bin:$PATH"
        make -j$(($(nproc) + 1)) || make -j1 V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-24.10-bin
        path: openwrt/bin/targets/
        retention-days: 7
