name: Build OpenWrt x86_64 (24.10)

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 24.10.config    # 修改此处文件名
  DIY_P1_SH: diy-24.10-part1.sh
  DIY_P2_SH: diy-24.10-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Free Disk Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 0

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev

      - name: Clone Source
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Load Feeds
        run: |
          cp $FEEDS_CONF openwrt/feeds.conf.default
          cd openwrt && ../$DIY_P1_SH

      - name: Update Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply Configurations
        run: |
          cp $CONFIG_FILE openwrt/.config    # 正确加载新配置文件
          cd openwrt && ../$DIY_P2_SH

      - name: Compile Firmware
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Firmware-24.10
          path: openwrt/bin/targets/x86/64/*
